name: Build and Release elf2uf2-rs

on:
  push:
  pull_request:

jobs:
  windows_build:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache rust builds
        uses: Swatinem/rust-cache@v2

      - name: Build Project
        run: cargo build --release

      # Publish a release (tagged commits)
      # For more info on options see: https://github.com/softprops/action-gh-release
      - name: Release (tag)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') # only publish tagged commits
        with:
          files: |
            target/release/*.exe
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
